name: mke_customer
description: Making Life Easier customer application.
version: 0.1.0+1
publish_to: none
environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  mke_ui:
    path: ../mke_ui
  mke_api:
    path: ../mke_api
  flutter_riverpod: ^2.6.1
  geolocator: ^13.0.2
  google_maps_flutter: ^2.10.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
