# Generated by Django 6.0.1 on 2026-07-30 10:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('schema_version', models.CharField(default='1.0', max_length=10)),
                ('event_type', models.CharField(max_length=100)),
                ('aggregate_type', models.CharField(max_length=50)),
                ('aggregate_id', models.CharField(max_length=100)),
                ('audience_group', models.CharField(max_length=150)),
                ('payload', models.JSONField(default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('occurred_at',),
                'indexes': [models.Index(fields=['published_at', 'occurred_at'], name='core_evento_publish_a51ee4_idx')],
            },
        ),
    ]
