# Generated by Django 6.0.1 on 2026-02-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_fare', models.DecimalField(decimal_places=2, default=2.0, max_digits=10)),
                ('price_per_km', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
