# Generated by Django 6.0.1 on 2026-07-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_pricingrule_surgepricing_zone_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricingrule',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='pricingrule',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('city', 'service_type'), name='one_active_pricing_rule_per_city_service'),
        ),
    ]
