# Generated by Django 6.0.1 on 2026-07-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_alter_pricingrule_unique_together_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pricingrule',
            constraint=models.CheckConstraint(condition=models.Q(('base_fare__gte', 0), ('per_km_rate__gte', 0), ('per_minute_rate__gte', 0)), name='pricing_rates_nonnegative'),
        ),
    ]
