# Generated by Django 6.0.1 on 2026-02-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='cancellation_count',
            field=models.IntegerField(default=0),
        ),
    ]
