# Generated by Django 6.0.1 on 2026-07-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driver_cancellation_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='license_plate',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
