# Generated by Django 6.0.1 on 2026-07-30 09:20

from django.db import migrations, models


def approve_existing_customer_roles(apps, schema_editor):
    AccountRole = apps.get_model("accounts", "AccountRole")
    AccountRole.objects.filter(role__name="customer").update(status="approved")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_role_alter_account_options_alter_account_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrole',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.RunPython(
            approve_existing_customer_roles,
            migrations.RunPython.noop,
        ),
    ]
