# Generated by Django 6.0.1 on 2026-07-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_onetimecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimecode',
            name='purpose',
            field=models.CharField(choices=[('phone_verification', 'Phone verification'), ('phone_login', 'Phone login'), ('password_reset', 'Password reset')], max_length=30),
        ),
    ]
