# Generated by Django 6.0.1 on 2026-02-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_driveravailability_current_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='dropoff_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='dropoff_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
