# Generated by Django 6.0.1 on 2026-02-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0006_ridemessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_cancellation_minutes', models.IntegerField(default=2)),
                ('rider_cancellation_fee', models.DecimalField(decimal_places=2, default=100.0, max_digits=8)),
                ('driver_cancellation_penalty_limit', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
