# Generated by Django 6.0.1 on 2026-07-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0007_cancellationconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('wallet', 'Wallet')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='trip',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
