# Generated by Django 6.0.1 on 2026-07-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0009_ride_start_pin_hash_trip_quoted_fare_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
