# Generated by Django 6.0.1 on 2026-07-30 09:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_phone_number'),
        ('wallets', '0002_transaction_wallet_transaction_amount_positive_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('available_balance__gte', 0)), name='wallet_available_balance_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('pending_balance__gte', 0)), name='wallet_pending_balance_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('debt_balance__gte', 0)), name='wallet_debt_balance_nonnegative'),
        ),
    ]
