# Generated by Django 6.0.1 on 2026-02-14 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_role_alter_account_options_alter_account_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('ride', 'Ride'), ('delivery', 'Delivery'), ('shop', 'Shop Order'), ('housing', 'Housing Booking'), ('job', 'Job Posting'), ('marketplace', 'Marketplace')], max_length=50)),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Percentage commission (e.g., 10.00 for 10%)', max_digits=5)),
                ('flat_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('effective_from', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.role')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
    ]
