# Generated by Django 6.0.1 on 2026-07-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_phone_number'),
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='commissionrule',
            constraint=models.CheckConstraint(condition=models.Q(('percentage__gte', 0), ('percentage__lte', 100)), name='commission_percentage_between_0_and_100'),
        ),
        migrations.AddConstraint(
            model_name='commissionrule',
            constraint=models.CheckConstraint(condition=models.Q(('flat_fee__gte', 0)), name='commission_flat_fee_nonnegative'),
        ),
    ]
